#!/bin/bash
#PBS -N speech_pipeline
#PBS -l select=1:ncpus=10:ngpus=4:mem=24gb
#PBS -l walltime=00:30:00
#PBS -q normal
#PBS -P Personal
#PBS -j oe
#PBS -o ./job_output.log
#PBS -e ./job_error.log

# --- Load modules ---
module load anaconda/2023.07
module load cuda/12.6  # adjust if needed

# --- Initialize Conda ---
export PATH="$HOME/miniconda3/bin:$PATH"
eval "$(conda shell.bash hook)"

# --- Activate env ---
conda activate solospeech

# --- Go to working dir ---
cd $PBS_O_WORKDIR

# --- Debug GPU ---
nvidia-smi

# --- Ensure PYTHONPATH includes project ---
export PYTHONPATH=$PBS_O_WORKDIR/SoloSpeech:$PBS_O_WORKDIR/geco:$PYTHONPATH

# --- Load ffmpeg ---
module load ffmpeg


# --- Run pipeline (SoloSpeech -> Whisper) ---
python3 main.py
